Migrate to null-safety
supabase/supabase-dart pull request #11
Opened 2021-03-04 03:50 UTC by TimWhiting

## What kind of change does this PR introduce?

Migrates to null safety

## What is the current behavior?

Using null unsafe dart

## What is the new behavior?

Using null safe dart

## Additional context

Addresses #10
Requires null-safe versions of postgrest, gotrue, and realtime to be published first, so it won't use path dependencies

2021-03-05 03:05 UTC, TimWhiting commented
@phamhieu 
Ready for review

2021-03-08 01:33 UTC, phamhieu requested changes

2021-03-08 01:33 UTC, phamhieu commented on CHANGELOG.md
>  ## [0.0.1-dev.9]
should be 0.0.1-dev.10

2021-03-08 01:33 UTC, phamhieu commented on lib/src/auth_user.dart
> +      String? aud,
I deployed gotrue-dart v0.0.1-dev.9 with update on User nullable params. Can you update to reflect the change.

2021-03-08 01:33 UTC, phamhieu commented on lib/src/auth_user.dart
> +      Map<String, dynamic>? appMetadata,
appMetadata and userMetadata should be not nullable

2021-03-08 01:33 UTC, phamhieu commented on lib/src/supabase.dart
> +  String? schema;
schema is not-nullable. to be 'public' as default

2021-03-08 01:33 UTC, phamhieu commented on lib/src/supabase.dart
> +  String? authUrl;
authUrl should be the same as restUrl and realtimeUrl

2021-03-08 03:29 UTC, TimWhiting commented
@phamhieu 
I made the changes requested and made a few more fields final to match the behavior and intentions.

2021-03-11 00:56 UTC, TimWhiting commented
@phamhieu 
Any other changes, or can this be merged?

2021-03-11 01:29 UTC, phamhieu requested changes

2021-03-11 01:29 UTC, phamhieu commented on lib/src/auth_user.dart
> +      required String lastSignInAt,
confirmedAt and lastSignInAt are nullable. So we don't need to required them.

2021-03-11 01:31 UTC, phamhieu commented
just 1 change left. otherwise lgtm 👍

2021-03-11 01:34 UTC, TimWhiting commented on lib/src/auth_user.dart
> +      required String lastSignInAt,
Done

2021-03-11 01:40 UTC, phamhieu commented on lib/src/auth_user.dart
> +      required String lastSignInAt,
actually, i'm not sure about the use-case for `AuthUser` https://github.com/supabase/supabase-dart/pull/6
for now, just follow exactly like `User` constructor on `gotrue-dart`.
```
User(
      {required this.id,
      required Map<String, dynamic>? appMetadata,
      required Map<String, dynamic>? userMetadata,
      required this.aud,
      required this.email,
      required this.createdAt,
      this.confirmedAt,
      this.lastSignInAt,
      required this.role,
      required this.updatedAt})
```

2021-03-11 01:40 UTC, phamhieu commented on lib/src/auth_user.dart
> +      required String lastSignInAt,
what do you think? @TimWhiting

2021-03-11 01:51 UTC, phamhieu approved these changes

2021-03-11 01:51 UTC, merged

2021-03-11 01:59 UTC, TimWhiting commented on lib/src/auth_user.dart
> +      required String lastSignInAt,
Yeah, I think the gotrue class should just be exported directly, rather than wrapping it. I'm not sure this class will be useful, and if it is, it can be added in later.