feat: add in_ filter on stream()
supabase/supabase-dart pull request #191
Opened 2023-04-09 01:29 UTC by dshukertjr

## What kind of change does this PR introduce?

Add support for the `in` filter to be used in `.stream()`. Same as the postgrest `in_` method, `in` is a reserved word in Dart, so had to change the filter from `in` to `in_`.

```dart
supabase.from('table').stream(primaryKey: ['id']).in_('name', ['Andy', 'Santiago', 'Holt']).listen();
```

2023-04-09 09:20 UTC, Vinzent03 requested changes

2023-04-09 09:20 UTC, Vinzent03 commented on lib/src/supabase_stream_builder.dart
> +            '${currentStreamFilter.column}=in.(${currentStreamFilter.value.join(',')})';
I think we need some additional `"` in case `currentStreamFilter.value` is a List of Strings containing `,` itself. I don't know how the realtime server handles them, but maybe do it like [here](https://github.com/supabase/postgrest-dart/blob/1b5583ca94df40a43d0d1d72d2f43a348f07f1ab/lib/src/postgrest_filter_builder.dart#L11)?

2023-04-09 14:10 UTC, bdlukaa commented
Have you considered `inFilter` or `filterIn`? I kinda find `in_` weird

2023-04-09 16:35 UTC, dshukertjr commented on lib/src/supabase_stream_builder.dart
> +            '${currentStreamFilter.column}=in.(${currentStreamFilter.value.join(',')})';
I have updated the code, and did some testing. It works with int and basic string not containing `,`, but it doesn't work with strings containing `,`. 

We could say it's a but on the realtime engine, but Supabase relatime isn't designed to cover every single query use case. If someone is trying to listen to values on the database with applying filters on a value with `,` in it, I'd say that particular person is doing something wrong. 

We can keep the code in case Realtime engine does become compatible with `,` values in the string, but we shouldn't stress too much about it.

2023-04-09 16:36 UTC, dshukertjr commented
@bdlukaa 
Great point! I have updated the code. We probably could update the name on postgrest methods too huh?

2023-04-11 08:58 UTC, Vinzent03 approved these changes

2023-04-12 03:04 UTC, merged